// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task/task.proto

//服务名

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//下面是消息体message的定义，可以暂时理解为go中的struct，其中的1，2，3...是每个变量唯一的编码
type Task struct {
	//每条任务的ID，本项目中对应mongodb记录的"_id"字段
	//@inject_tag: bson:"_id" form:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//任务主体文字
	//@inject_tag: bson:"body" form:"body"
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	//用户设定的任务开始时间戳
	//@inject_tag: bson:"startTime" form:"startTime"
	StartTime int64 `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	//用户设定的任务截止时间戳
	//@inject_tag: bson:"endTime" form:"endTime"
	EndTime int64 `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	//任务是否已完成
	//@inject_tag: bson:"isFinished" form:"isFinished"
	IsFinished int32 `protobuf:"varint,5,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	//用户实际完成时间戳
	//@inject_tag: bson:"finishTime" form:"finishTime"
	FinishTime int64 `protobuf:"varint,6,opt,name=finishTime,proto3" json:"finishTime,omitempty"`
	//任务创建时间
	//@inject_tag: bson:"createTime" form:"createTime"
	CreateTime int64 `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	//任务修改时间
	//@inject_tag: bson:"updateTime" form:"updateTime"
	UpdateTime int64 `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	//用户ID
	//@inject_tag: bson:"userId" form:"userId"
	UserId               string   `protobuf:"bytes,9,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Task) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Task) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Task) GetIsFinished() int32 {
	if m != nil {
		return m.IsFinished
	}
	return 0
}

func (m *Task) GetFinishTime() int64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *Task) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Task) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Task) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//增删改接口返回参数
type EditResponse struct {
	//操作返回的消息
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{1}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//查询接口的参数
type SearchRequest struct {
	//分页查询页码，从第一页开始
	//@inject_tag: form:"pageSize"
	PageSize int64 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//分页查询每页数量，默认20
	//@inject_tag: form:"pageCode"
	PageCode int64 `protobuf:"varint,2,opt,name=pageCode,proto3" json:"pageCode,omitempty"`
	// 排序字段
	//@inject_tag: form:"sortBy"
	SortBy string `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	// 顺序 -1降序 1升序
	//@inject_tag: form:"order"
	Order int32 `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	//关键字模糊查询任务body字段
	//@inject_tag: form:"keyword"
	Keyword              string   `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchRequest) GetPageCode() int64 {
	if m != nil {
		return m.PageCode
	}
	return 0
}

func (m *SearchRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchRequest) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *SearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchResponse struct {
	//分页查询页码，从第一页开始
	//@inject_tag: form:"pageSize"
	PageSize int64 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//分页查询每页数量，默认20
	//@inject_tag: form:"pageCode"
	PageCode int64 `protobuf:"varint,2,opt,name=pageCode,proto3" json:"pageCode,omitempty"`
	// 排序字段
	//@inject_tag: form:"sortBy"
	SortBy string `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	// 顺序 -1降序 1升序
	//@inject_tag: form:"order"
	Order int32 `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	//数据总数
	//@inject_tag: form:"total"
	Total int64 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	//具体数据，这里repeated表示可以出现多条，类似于go中的slice
	//@inject_tag: form:"rows"
	Rows                 []*Task  `protobuf:"bytes,6,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{3}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchResponse) GetPageCode() int64 {
	if m != nil {
		return m.PageCode
	}
	return 0
}

func (m *SearchResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchResponse) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *SearchResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResponse) GetRows() []*Task {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "go.micro.service.task.Task")
	proto.RegisterType((*EditResponse)(nil), "go.micro.service.task.EditResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.service.task.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.service.task.SearchResponse")
}

func init() { proto.RegisterFile("proto/task/task.proto", fileDescriptor_152e577c5c92a6d4) }

var fileDescriptor_152e577c5c92a6d4 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xfc, 0xa7, 0xf1, 0xb4, 0x54, 0x68, 0xd5, 0x22, 0x2b, 0x20, 0x64, 0x19, 0x90,
	0x7c, 0x72, 0xa5, 0xf2, 0x06, 0x2d, 0x20, 0x21, 0x01, 0x87, 0x4d, 0x25, 0x24, 0x6e, 0xae, 0x77,
	0x9a, 0xae, 0xd2, 0x64, 0xcd, 0xee, 0x86, 0xc8, 0xbc, 0x04, 0xaf, 0xc0, 0x8b, 0xf0, 0x62, 0x9c,
	0xd0, 0x8e, 0xed, 0x38, 0x48, 0x04, 0x2e, 0x51, 0x2f, 0xd1, 0x7c, 0xf3, 0x9b, 0x19, 0x4d, 0xbe,
	0x1d, 0x19, 0x4e, 0x6b, 0xad, 0xac, 0x3a, 0xb3, 0xa5, 0x99, 0xd3, 0x4f, 0x41, 0x9a, 0x9d, 0xce,
	0x54, 0xb1, 0x90, 0x95, 0x56, 0x85, 0x41, 0xfd, 0x55, 0x56, 0x58, 0x38, 0x98, 0xfd, 0xf2, 0x20,
	0xb8, 0x2a, 0xcd, 0x9c, 0x1d, 0xc3, 0x48, 0x8a, 0xc4, 0x4b, 0xbd, 0x3c, 0xe6, 0x23, 0x29, 0x18,
	0x83, 0xe0, 0x5a, 0x89, 0x26, 0x19, 0x51, 0x86, 0x62, 0xf6, 0x14, 0x62, 0x63, 0x4b, 0x6d, 0xaf,
	0xe4, 0x02, 0x13, 0x3f, 0xf5, 0x72, 0x9f, 0x0f, 0x09, 0x96, 0xc0, 0x01, 0x2e, 0x05, 0xb1, 0x80,
	0x58, 0x2f, 0xd9, 0x33, 0x00, 0x69, 0xde, 0xca, 0xa5, 0x34, 0xb7, 0x28, 0x92, 0x30, 0xf5, 0xf2,
	0x90, 0x6f, 0x65, 0x1c, 0xbf, 0xa1, 0x98, 0x9a, 0x23, 0x6a, 0xde, 0xca, 0x38, 0x5e, 0x69, 0x2c,
	0x2d, 0x12, 0x3f, 0x68, 0xf9, 0x90, 0x71, 0x7c, 0x55, 0x8b, 0x9e, 0x8f, 0x5b, 0x3e, 0x64, 0xd8,
	0x63, 0x88, 0x56, 0x06, 0xf5, 0x3b, 0x91, 0xc4, 0xf4, 0x6f, 0x3a, 0x95, 0xa5, 0x70, 0xf4, 0x46,
	0x48, 0xcb, 0xd1, 0xd4, 0x6a, 0x69, 0x90, 0x3d, 0x02, 0x7f, 0x61, 0x66, 0x9d, 0x09, 0x2e, 0xcc,
	0xbe, 0x7b, 0xf0, 0x70, 0x8a, 0xa5, 0xae, 0x6e, 0x39, 0x7e, 0x59, 0xa1, 0xb1, 0x6c, 0x02, 0xe3,
	0xba, 0x9c, 0xe1, 0x54, 0x7e, 0x43, 0x2a, 0xf4, 0xf9, 0x46, 0xf7, 0xec, 0x52, 0x09, 0x24, 0xdf,
	0x3a, 0xe6, 0xb4, 0xdb, 0xc1, 0x28, 0x6d, 0x2f, 0x1a, 0x32, 0x2e, 0xe6, 0x9d, 0x62, 0x27, 0x10,
	0x2a, 0x2d, 0x50, 0x93, 0x67, 0x21, 0x6f, 0x85, 0xf3, 0x72, 0x8e, 0xcd, 0x5a, 0xe9, 0xd6, 0xae,
	0x98, 0xf7, 0x32, 0xfb, 0xe9, 0xc1, 0x71, 0xbf, 0x51, 0xb7, 0xf6, 0xfd, 0xac, 0x74, 0x02, 0xa1,
	0x55, 0xb6, 0xbc, 0xa3, 0x85, 0x7c, 0xde, 0x0a, 0x76, 0x06, 0x81, 0x56, 0x6b, 0x93, 0x44, 0xa9,
	0x9f, 0x1f, 0x9e, 0x3f, 0x29, 0xfe, 0x7a, 0x65, 0x85, 0xbb, 0x30, 0x4e, 0x85, 0xe7, 0x3f, 0x7c,
	0x38, 0x74, 0x72, 0xda, 0x72, 0xf6, 0x1e, 0xa2, 0x4b, 0x7a, 0x49, 0xf6, 0xaf, 0xe6, 0xc9, 0xf3,
	0x1d, 0x70, 0xfb, 0xfd, 0xb2, 0x07, 0x6e, 0xda, 0x6b, 0xbc, 0xc3, 0xfd, 0x4d, 0xfb, 0xa0, 0x84,
	0xbc, 0x69, 0xf6, 0x32, 0xed, 0x23, 0x8c, 0x37, 0x17, 0xbf, 0x8f, 0x79, 0x9f, 0x20, 0x6a, 0x0f,
	0x81, 0xbd, 0xd8, 0xd1, 0xf0, 0xc7, 0xe5, 0x4e, 0x5e, 0xfe, 0xa7, 0xaa, 0x1f, 0x7c, 0x71, 0xf4,
	0x19, 0x86, 0x6f, 0xc8, 0x75, 0x44, 0xf1, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xc7,
	0x5a, 0x74, 0x58, 0x04, 0x00, 0x00,
}
